name: dockerhub-2
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-dockerhub
      - manual-trigger-dockerhub-2
  schedule:
    - cron: '15 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://registry-1.docker.io
          OCI_NAMESPACE: REPLACEME/REPLACEME
          OCI_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          OCI_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          OCI_TEST_PUSH: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/dockerhub/push/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
