name: ecr-1
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-ecr
      - manual-trigger-ecr-1
  schedule:
    - cron: '20 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Amazon access token
        run: |
          export ECR_ACCESS_TOKEN="$(aws --region=us-east-1 ecr get-login --no-include-email | awk '{print $6}')"
          echo "::add-mask::${ECR_ACCESS_TOKEN}"
          echo "::set-env name=ECR_ACCESS_TOKEN::${ECR_ACCESS_TOKEN}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_ACCESS_AWS_SECRET_ACCESS_KEY }}
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://741920044080.dkr.ecr.us-east-1.amazonaws.com
          OCI_USERNAME: AWS
          OCI_PASSWORD: ${{ env.ECR_ACCESS_TOKEN }}
          OCI_NAMESPACE: distribution-test
          OCI_TEST_PULL: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/ecr/pull/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
