name: gcr-1
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-gcr
      - manual-trigger-gcr-1
  schedule:
    - cron: '25 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Google access token
        run: |
          echo ${GCLOUD_SERVICE_KEY} | base64 -d > ./credentials.json
          trap "rm -f ./credentials.json" EXIT
          gcloud auth activate-service-account REPLACEME@REPLACEME.iam.gserviceaccount.com --key-file="./credentials.json" --project=REPLACEME
          export GCLOUD_ACCESS_TOKEN="$(gcloud auth print-access-token)"
          echo "::add-mask::${GCLOUD_ACCESS_TOKEN}"
          echo "::set-env name=GCLOUD_ACCESS_TOKEN::${GCLOUD_ACCESS_TOKEN}"
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://gcr.io
          OCI_USERNAME: oauth2accesstoken
          OCI_PASSWORD: ${{ env.GCLOUD_ACCESS_TOKEN }}
          OCI_NAMESPACE: REPLACEME/REPLACEME
          OCI_TEST_PULL: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/gcr/pull/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
