name: github-3
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-github
      - manual-trigger-github-3
  schedule:
    - cron: '30 6 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@master
        env:
          OCI_ROOT_URL: https://docker.pkg.github.com
          OCI_USERNAME: opencontainers
          OCI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          OCI_NAMESPACE: opencontainers/oci-conformance/distribution-test
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/github/content-discovery/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
