name: jcr-2
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-jcr
      - manual-trigger-jcr-2
  schedule:
    - cron: '40 6 * * *'
jobs:
  run:
    services:
      jcr:
        image: docker.bintray.io/jfrog/artifactory-jcr:latest
        ports:
          - 8081:8081
    runs-on: ubuntu-latest
    steps:
      - name: Wait for JCR to be ready
        run: timeout 200 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/ping)" != "200" ]]; do sleep 5; done' || false
      - name: Checkout Workspace
        uses: actions/checkout@v2
      - name: Apply conformance config to JCR
        run: curl -u admin:password -X POST -H "Content-type:application/xml" --data-binary "@$GITHUB_WORKSPACE/.github/config/jcr/artifactory.config.import.xml"  http://localhost:${{ job.services.jcr.ports['8081'] }}/artifactory/api/system/configuration
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@master
        env:
          OCI_ROOT_URL: http://jcr:8081
          OCI_USERNAME: admin
          OCI_PASSWORD: password
          OCI_NAMESPACE: conformance-local/oci-conformance-test
          OCI_TEST_PUSH: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/jcr/push/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
