name: trow-4
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-trow
      - manual-trigger-trow-4
  schedule:
    - cron: '50 6 * * *'
jobs:
  run:
    services:
      trow:
        image: quay.io/bloodorange/trow:b54f366-fork # TODO: use containersolutions-provided image
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: bloodorangeio/distribution-spec@master
        env:
          OCI_ROOT_URL: http://trow:8000
          OCI_NAMESPACE: oci-conformance/distribution-test
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - name: Upload test report to S3
        run: aws s3 cp --acl public-read report.html s3://oci-conformance/distribution-spec/trow/content-management/report.html
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_AWS_SECRET_ACCESS_KEY }}
